receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 8192
    timeout: 5s

exporters:
  debug:
    verbosity: basic

  # 1. Экспортер для Трейсов
  kafka/traces:
    brokers: ["kafka:9092"]
    topic: "telemetry-traces"
    encoding: otlp_json
    retry_on_failure:
      enabled: true

  # 2. Экспортер для Метрик
  kafka/metrics:
    brokers: ["kafka:9092"]
    topic: "telemetry-metrics"
    encoding: otlp_json
    retry_on_failure:
      enabled: true

  # 3. Экспортер для Логов
  kafka/logs:
    brokers: ["kafka:9092"]
    topic: "telemetry-logs"
    encoding: otlp_json
    retry_on_failure:
      enabled: true

service:
  pipelines:
    # Трейсы отправляем в свой топик + дублируем в консоль для теста
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka/traces, debug]
    
    # Метрики — в свой
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka/metrics, debug]

    # Логи — в свой
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka/logs, debug]