spring:
  application:
    name: FitnessTracker
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  tracing:
    sampling:
      probability: 1.0

  otlp:
    metrics:
      export:
        url: http://${OTEL_COLLECTOR_HOST:localhost}:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://${OTEL_COLLECTOR_HOST:localhost}:4318/v1/traces

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]"
