name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build & test with Maven
        run: mvn clean verify

      - name: Build Docker image
        run: docker build -t fitness-tracker:ci -f Dockerfile .
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fitness-tracker:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fitness-tracker:latest
  
